/**
 * AI service layer.
 *
 * Meeting summaries, research briefs and chat replies are generated by a real
 * model through server functions (the API key stays server-side). Email drafts
 * and work plans are composed deterministically from the user's own input.
 */

import { chatFn, researchFn, summarizeMeetingFn } from "./ai.functions";


export type Tone = "Formal" | "Friendly" | "Professional" | "Persuasive";

const DELAY = 900;

function simulate<T>(value: T, ms = DELAY): Promise<T> {
  return new Promise((resolve) => setTimeout(() => resolve(value), ms));
}

function clean(text: string) {
  return text.trim().replace(/\s+/g, " ");
}

function sentences(text: string): string[] {
  return text
    .split(/\n+|(?<=[.!?])\s+/)
    .map((s) => s.trim())
    .filter((s) => s.length > 2);
}

function titleCase(text: string) {
  return text.charAt(0).toUpperCase() + text.slice(1);
}

/* ------------------------------- Email ---------------------------------- */

export interface EmailInput {
  recipient: string;
  purpose: string;
  context: string;
  tone: Tone;
  instructions?: string;
}

const openers: Record<Tone, (r: string) => string> = {
  Formal: (r) => `Dear ${r},`,
  Friendly: (r) => `Hi ${r},`,
  Professional: (r) => `Hello ${r},`,
  Persuasive: (r) => `Hello ${r},`,
};

const closers: Record<Tone, string> = {
  Formal: "Yours sincerely,",
  Friendly: "Thanks so much,",
  Professional: "Kind regards,",
  Persuasive: "Looking forward to your response,",
};

const bridges: Record<Tone, string> = {
  Formal:
    "I am writing to you regarding the matter set out below, and would appreciate your consideration.",
  Friendly: "I wanted to reach out quickly about something I think you'll find useful.",
  Professional: "I'm getting in touch to share some context and agree on the next steps.",
  Persuasive:
    "I believe there is a clear opportunity here, and I'd like to walk you through why it matters.",
};

export async function generateEmail(input: EmailInput): Promise<string> {
  const recipient = clean(input.recipient) || "there";
  const purpose = clean(input.purpose) || "a quick update";
  const context = clean(input.context) || "There are no additional details at this stage.";
  const extra = clean(input.instructions || "");

  const subject = titleCase(purpose).replace(/\.$/, "");
  const points = sentences(input.context).slice(0, 3);

  const body = [
    `Subject: ${subject}`,
    "",
    openers[input.tone](recipient),
    "",
    bridges[input.tone],
    "",
    `${titleCase(context)}`,
    points.length > 1
      ? ["", "Key points:", ...points.map((p) => `• ${p.replace(/\.$/, "")}`)].join("\n")
      : "",
    extra ? `\n${titleCase(extra)}` : "",
    "",
    input.tone === "Persuasive"
      ? "If this sounds workable, I'd be glad to set up a short call this week to move it forward."
      : "Please let me know if you would like any further detail, or if a short call would be easier.",
    "",
    closers[input.tone],
    "[Your name]",
    "[Your role · Your organisation]",
  ]
    .filter((line) => line !== "")
    .join("\n")
    .replace(/\n{3,}/g, "\n\n");

  return simulate(body);
}

/* ---------------------------- Meeting notes ------------------------------ */

export async function summarizeMeeting(notes: string): Promise<string> {
  if (!notes.trim()) return "";
  return summarizeMeetingFn({ data: { notes: notes.trim() } });
}

/* ------------------------------- Planner --------------------------------- */

export type Priority = "High" | "Medium" | "Low";

export interface PlannerTask {
  id: string;
  name: string;
  deadline: string;
  priority: Priority;
  duration: number; // hours
}

export interface PlannerInput {
  tasks: PlannerTask[];
  hoursPerDay: number;
  startHour: number;
  mode: "Daily" | "Weekly";
}

function fmtHour(h: number) {
  const hour = Math.floor(h);
  const min = Math.round((h - hour) * 60);
  const suffix = hour >= 12 ? "PM" : "AM";
  const display = hour % 12 === 0 ? 12 : hour % 12;
  return `${display}:${min.toString().padStart(2, "0")} ${suffix}`;
}

export async function generatePlan(input: PlannerInput): Promise<string> {
  const order: Priority[] = ["High", "Medium", "Low"];
  const sorted = [...input.tasks].sort(
    (a, b) => order.indexOf(a.priority) - order.indexOf(b.priority),
  );

  const days =
    input.mode === "Weekly"
      ? ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
      : ["Today"];

  const buckets: string[] = [];
  let dayIndex = 0;
  let cursor = input.startHour;
  let used = 0;

  for (const task of sorted) {
    if (used + task.duration > input.hoursPerDay && dayIndex < days.length - 1) {
      dayIndex += 1;
      cursor = input.startHour;
      used = 0;
    }
    const end = cursor + task.duration;
    buckets.push(
      `${days[dayIndex]} · ${fmtHour(cursor)} – ${fmtHour(end)} · [${task.priority}] ${task.name}${
        task.deadline ? ` (due ${task.deadline})` : ""
      }`,
    );
    cursor = end + 0.25;
    used += task.duration;
  }

  const byPriority = (p: Priority) =>
    sorted.filter((t) => t.priority === p).map((t) => `• ${t.name} — ${t.duration}h`);

  const total = sorted.reduce((sum, t) => sum + t.duration, 0);

  const out = [
    `${input.mode.toUpperCase()} WORK PLAN`,
    `${sorted.length} task${sorted.length === 1 ? "" : "s"} · ${total}h of focused work · ${input.hoursPerDay}h available per day`,
    "",
    "HIGH PRIORITY",
    ...(byPriority("High").length ? byPriority("High") : ["• None"]),
    "",
    "MEDIUM PRIORITY",
    ...(byPriority("Medium").length ? byPriority("Medium") : ["• None"]),
    "",
    "LOW PRIORITY",
    ...(byPriority("Low").length ? byPriority("Low") : ["• None"]),
    "",
    "SUGGESTED TIME BLOCKS",
    ...buckets,
    "",
    "WORKING NOTES",
    "• Protect the first block of the day for the highest-priority task.",
    "• Keep a 15-minute buffer between blocks for overrun and messages.",
    total > input.hoursPerDay * days.length
      ? "• The workload exceeds the hours available — consider moving low-priority items or renegotiating a deadline."
      : "• The workload fits inside the hours you entered.",
  ].join("\n");

  return simulate(out, 800);
}

/* ------------------------------- Research -------------------------------- */

export interface ResearchInput {
  topic: string;
  question: string;
  context: string;
  length: "Short" | "Standard" | "Detailed";
}

export async function generateResearch(input: ResearchInput): Promise<string> {
  return researchFn({
    data: {
      topic: clean(input.topic),
      question: clean(input.question),
      context: input.context.trim(),
      length: input.length,
    },
  });
}

/* --------------------------------- Chat ---------------------------------- */

export interface ChatTurn {
  role: "user" | "assistant";
  content: string;
}

export async function chatReply(message: string, history: ChatTurn[] = []): Promise<string> {
  const messages = [...history.slice(-16), { role: "user" as const, content: message.trim() }];
  return chatFn({ data: { messages } });
}
